- header: |
    DeepLabCut Toolbox (deeplabcut.org)
    © A. & M. Mathis Labs
    https://github.com/DeepLabCut/DeepLabCut

    Please see AUTHORS for contributors.
    https://github.com/DeepLabCut/DeepLabCut/blob/master/AUTHORS

    Licensed under GNU Lesser General Public License v3.0
  include:
    - 'deeplabcut/**/*.py'
    - 'tests/**/*.py' 
    - 'examples/**/*.py'
  exclude:
    - deeplabcut/pose_estimation_tensorflow/backbones/* 
    - deeplabcut/pose_estimation_tensorflow/datasets/*
    - deeplabcut/pose_estimation_tensorflow/lib/*
    - deeplabcut/pose_estimation_tensorflow/nnets/*
    - deeplabcut/pose_estimation_tensorflow/util/*
    - deeplabcut/pose_tracking_pytorch/solver/scheduler_factory.py
