version: 2.1

orbs:
  python: circleci/python@4.0.0

jobs:
  build-and-test:
    executor:
      name: python/default
      tag: '3.10'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: uv
      - run:
          name: TestDLC
          # uv handles the installation of the dependencies
          command: uv run python testscript_cli.py

workflows:
  main:
    jobs:
      - build-and-test