version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    working_directory: ~/circleci-demo-python-django
    docker:
      - image: circleci/python:3.7.9  # primary container for the build job
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python testscript_cli.py
          name: TestDLC

workflows:
  main:
    jobs:
      - build-and-test