data:
  inference:
    auto_padding: # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
model:
  backbone:
    type: HRNet
    model_name: hrnet_w18
    freeze_bn_stats: true
    freeze_bn_weights: false
    interpolate_branches: false
    increased_channel_count: false  # changes backbone_output_channels to 128 when true
  backbone_output_channels: 18
