model:
  backbone:
    type: ResNet
    model_name: resnet101
    output_stride: 16
    freeze_bn_stats: false
    freeze_bn_weights: false
  backbone_output_channels: 2048
runner:
  optimizer:
    type: AdamW
    params:
      lr: 0.001
  scheduler:
    type: LRListScheduler
    params:
      lr_list: [ [ 1e-4 ], [ 1e-5 ] ]
      milestones: [ 90, 120 ]
