all_joints:
- - 0
- - 1
- - 2
- - 3
- - 4
all_joints_names:
- bodypart1
- bodypart2
- bodypart3
- corner1
- corner2
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
crop_sampling: hybrid
crop_size:
- 200
- 200
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_multi_mouseApr12/multi_mouse_dlc_team80shuffle1.pickle
dataset_type: multi-animal-imgaug
decay_steps: 30000
display_iters: 2
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.5
histeq: true
histeqratio: 0.1
init_weights: /Users/Jessy/PycharmProjects/DeepLabCut/deeplabcut/pose_estimation_tensorflow/models/pretrained/efficientnet-b0/model.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
max_shift: 0.4
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_multi_mouseApr12/Documentation_data-multi_mouse_80shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: efficientnet-b0
num_idchannel: 3
num_joints: 5
num_limbs: 3
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 0
  - 2
- - 1
  - 2
partaffinityfield_predict: true
pos_dist_thresh: 17
pre_resize: []
project_path: /Users/Jessy/PycharmProjects/DeepLabCut/examples/multi_mouse-dlc_team-2022-04-12
rotation: 25
rotratio: 0.4
save_iters: 5
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
weigh_only_present_joints: false
