Collections:
  - Name: RetinaNet
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x V100 GPUs
      Architecture:
        - Focal Loss
        - FPN
        - ResNet
    Paper:
      URL: https://arxiv.org/abs/1708.02002
      Title: "Focal Loss for Dense Object Detection"
    README: configs/retinanet/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.0.0/mmdet/models/detectors/retinanet.py#L6
      Version: v2.0.0

Models:
  - Name: retinanet_r50_caffe_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r50_caffe_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 3.5
      inference time (ms/im):
        - value: 53.76
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.3
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_caffe_fpn_1x_coco/retinanet_r50_caffe_fpn_1x_coco_20200531-f11027c5.pth

  - Name: retinanet_r50_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 3.8
      inference time (ms/im):
        - value: 52.63
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_1x_coco/retinanet_r50_fpn_1x_coco_20200130-c2398f9e.pth

  - Name: retinanet_r50_fpn_fp16_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r50_fpn_fp16_1x_coco.py
    Metadata:
      Training Memory (GB): 2.8
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
        - Mixed Precision Training
      inference time (ms/im):
        - value: 31.65
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP16
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/fp16/retinanet_r50_fpn_fp16_1x_coco/retinanet_r50_fpn_fp16_1x_coco_20200702-0dbfb212.pth

  - Name: retinanet_r50_fpn_2x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r50_fpn_2x_coco.py
    Metadata:
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_2x_coco/retinanet_r50_fpn_2x_coco_20200131-fdb43119.pth

  - Name: retinanet_r50_fpn_mstrain_3x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r50_fpn_mstrain_640-800_3x_coco.py
    Metadata:
      Epochs: 36
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r50_fpn_mstrain_3x_coco/retinanet_r50_fpn_mstrain_3x_coco_20210718_220633-88476508.pth

  - Name: retinanet_r101_caffe_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r101_caffe_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 5.5
      inference time (ms/im):
        - value: 68.03
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r101_caffe_fpn_1x_coco/retinanet_r101_caffe_fpn_1x_coco_20200531-b428fa0f.pth

  - Name: retinanet_r101_caffe_fpn_mstrain_3x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r101_caffe_fpn_1x_coco.py
    Metadata:
      Epochs: 36
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.7
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r101_caffe_fpn_mstrain_3x_coco/retinanet_r101_caffe_fpn_mstrain_3x_coco_20210721_063439-88a8a944.pth

  - Name: retinanet_r101_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r101_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 5.7
      inference time (ms/im):
        - value: 66.67
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r101_fpn_1x_coco/retinanet_r101_fpn_1x_coco_20200130-7a93545f.pth

  - Name: retinanet_r101_fpn_2x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r101_fpn_2x_coco.py
    Metadata:
      Training Memory (GB): 5.7
      inference time (ms/im):
        - value: 66.67
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 38.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r101_fpn_2x_coco/retinanet_r101_fpn_2x_coco_20200131-5560aee8.pth

  - Name: retinanet_r101_fpn_mstrain_3x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_r101_fpn_2x_coco.py
    Metadata:
      Epochs: 36
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_r101_fpn_mstrain_3x_coco/retinanet_r101_fpn_mstrain_3x_coco_20210720_214650-7ee888e0.pth

  - Name: retinanet_x101_32x4d_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_x101_32x4d_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 7.0
      inference time (ms/im):
        - value: 82.64
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 39.9
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_x101_32x4d_fpn_1x_coco/retinanet_x101_32x4d_fpn_1x_coco_20200130-5c8b7ec4.pth

  - Name: retinanet_x101_32x4d_fpn_2x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_x101_32x4d_fpn_2x_coco.py
    Metadata:
      Training Memory (GB): 7.0
      inference time (ms/im):
        - value: 82.64
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_x101_32x4d_fpn_2x_coco/retinanet_x101_32x4d_fpn_2x_coco_20200131-237fc5e1.pth

  - Name: retinanet_x101_64x4d_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_x101_64x4d_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 10.0
      inference time (ms/im):
        - value: 114.94
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.0
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_x101_64x4d_fpn_1x_coco/retinanet_x101_64x4d_fpn_1x_coco_20200130-366f5af1.pth

  - Name: retinanet_x101_64x4d_fpn_2x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_x101_64x4d_fpn_2x_coco.py
    Metadata:
      Training Memory (GB): 10.0
      inference time (ms/im):
        - value: 114.94
          hardware: V100
          backend: PyTorch
          batch size: 1
          mode: FP32
          resolution: (800, 1333)
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.8
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_x101_64x4d_fpn_2x_coco/retinanet_x101_64x4d_fpn_2x_coco_20200131-bca068ab.pth

  - Name: retinanet_x101_64x4d_fpn_mstrain_3x_coco
    In Collection: RetinaNet
    Config: configs/retinanet/retinanet_x101_64x4d_fpn_mstrain_640-800_3x_coco.py
    Metadata:
      Epochs: 36
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/retinanet/retinanet_x101_64x4d_fpn_mstrain_3x_coco/retinanet_x101_64x4d_fpn_mstrain_3x_coco_20210719_051838-022c2187.pth
