blank_issues_enabled: false
contact_links:
- name: deeplabcut forum
  url: https://forum.image.sc/tag/deeplabcut
  about: Please ask general questions here
- name: deeplabcut gitter
  url: https://gitter.im/DeepLabCut/community
  about: Chat with the community
