ARG CUDA_VERSION=11.4.0-cudnn8-runtime-ubuntu20.04
ARG DEEPLABCUT_VERSION=2.2.1.1
FROM deeplabcut/deeplabcut:${DEEPLABCUT_VERSION}-base-cuda${CUDA_VERSION}

ENV DLClight True

COPY motd.sh /home/motd.sh
RUN echo "source /home/motd.sh" >> /etc/profile
