ARG CUDA_VERSION
ARG CUDNN_VERSION
ARG DEEPLABCUT_VERSION
FROM deeplabcut/deeplabcut:${DEEPLABCUT_VERSION}-base-cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}

ENV DLClight True

COPY motd.sh /home/motd.sh
RUN echo "source /home/motd.sh" >> /etc/profile
