FROM deeplabcut/deeplabcut:base

RUN DEBIAN_FRONTEND=noninteractive apt-get update -yy \ 
    && DEBIAN_FRONTEND=noninteractive apt-get install -yy --no-install-recommends libgtk-3-dev python3-wxgtk4.0 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

ENV DLClight False
