ARG CUDA_VERSION
ARG CUDNN_VERSION
ARG DEEPLABCUT_VERSION
FROM deeplabcut/deeplabcut:${DEEPLABCUT_VERSION}-core-cuda${CUDA_VERSION}-cudnn${CUDNN_VERSION}

RUN mkdir test/
WORKDIR test
RUN apt-get update && apt-get install -yy git
RUN git config --global advice.detachedHead false
# FIXME(maxim): pull from --branch v${DEEPLABCUT_VERSION}
RUN git clone --depth 1 --branch main \
    https://github.com/DeepLabCut/DeepLabCut.git /test

RUN pip3 install --no-cache-dir pytest
RUN chmod a+rwx -R /test
