all_joints:
- - 0
- - 1
- - 2
- - 3
all_joints_names:
- head
- tail
- leftwing
- rightwing
batch_size: 16
bottomheight: 400
crop: true
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_MontBlancDec16/MontBlanc_Daniel95shuffle0.pickle
dataset_type: multi-animal-imgaug
display_iters: 500
global_scale: 0.8
init_weights: /usr/local/lib/python3.6/dist-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_MontBlancDec16/Documentation_data-MontBlanc_95shuffle0.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.0001
  - 7500
- - 5.0e-05
  - 12000
- - 1.0e-05
  - 200000
net_type: resnet_50
num_joints: 4
num_limbs: 6
optimizer: adam
pafwidth: 20
pairwise_huber_loss: false
pairwise_loss_weight: 0.1
pairwise_predict: false
partaffinityfield_graph:
- - 0
  - 1
- - 2
  - 3
- - 0
  - 2
- - 0
  - 3
- - 2
  - 1
- - 3
  - 1
partaffinityfield_predict: true
pos_dist_thresh: 17
project_path: /media/alex/dropboxdisk/Dropbox/Collaborations/Cancer/DLCdev/examples-multianimal/MontBlanc-Daniel-2019-12-16
rightwidth: 400
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
weigh_only_present_joints: false
