Collections:
  - Name: TOOD
    Metadata:
      Training Data: COCO
      Training Techniques:
        - SGD
      Training Resources: 8x V100 GPUs
      Architecture:
        - TOOD
    Paper:
      URL: https://arxiv.org/abs/2108.07755
      Title: 'TOOD: Task-aligned One-stage Object Detection'
    README: configs/tood/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.20.0/mmdet/models/detectors/tood.py#L7
      Version: v2.20.0

Models:
  - Name: tood_r101_fpn_mstrain_2x_coco
    In Collection: TOOD
    Config: configs/tood/tood_r101_fpn_mstrain_2x_coco.py
    Metadata:
      Training Memory (GB): 6.0
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tood/tood_r101_fpn_mstrain_2x_coco/tood_r101_fpn_mstrain_2x_coco_20211210_144232-a18f53c8.pth

  - Name: tood_x101_64x4d_fpn_mstrain_2x_coco
    In Collection: TOOD
    Config: configs/tood/tood_x101_64x4d_fpn_mstrain_2x_coco.py
    Metadata:
      Training Memory (GB): 10.2
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 47.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tood/tood_x101_64x4d_fpn_mstrain_2x_coco/tood_x101_64x4d_fpn_mstrain_2x_coco_20211211_003519-a4f36113.pth

  - Name: tood_r101_fpn_dconv_c3-c5_mstrain_2x_coco
    In Collection: TOOD
    Config: configs/tood/tood_r101_fpn_dconv_c3-c5_mstrain_2x_coco.py
    Metadata:
      Training Memory (GB): 6.2
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 49.3
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tood/tood_r101_fpn_dconv_c3-c5_mstrain_2x_coco/tood_r101_fpn_dconv_c3-c5_mstrain_2x_coco_20211210_213728-4a824142.pth

  - Name: tood_r50_fpn_anchor_based_1x_coco
    In Collection: TOOD
    Config: configs/tood/tood_r50_fpn_anchor_based_1x_coco.py
    Metadata:
      Training Memory (GB): 4.1
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 42.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tood/tood_r50_fpn_anchor_based_1x_coco/tood_r50_fpn_anchor_based_1x_coco_20211214_100105-b776c134.pth

  - Name: tood_r50_fpn_1x_coco
    In Collection: TOOD
    Config: configs/tood/tood_r50_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 4.1
      Epochs: 12
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 42.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tood/tood_r50_fpn_1x_coco/tood_r50_fpn_1x_coco_20211210_103425-20e20746.pth

  - Name: tood_r50_fpn_mstrain_2x_coco
    In Collection: TOOD
    Config: configs/tood/tood_r50_fpn_mstrain_2x_coco.py
    Metadata:
      Training Memory (GB): 4.1
      Epochs: 24
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.5
    Weights: https://download.openmmlab.com/mmdetection/v2.0/tood/tood_r50_fpn_mstrain_2x_coco/tood_r50_fpn_mstrain_2x_coco_20211210_144231-3b23174c.pth
