data:
  inference:
    auto_padding:  # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
    bu_snapshot: /home/lucas/datasets/trimice-dlc-2021-06-22/dlc-models-pytorch/iteration-17/trimiceJun22-trainset95shuffle1/train/snapshot-best.pth
    #bu_predictions: /home/lucas/datasets/trimice-dlc-2021-06-22/evaluation-results-pytorch/iteration-17/trimiceJun22-trainset95shuffle1/DLC_DekrW32_trimiceJun22shuffle1_best.h5
    #bu_predictions: /home/lucas/datasets/fish-dlc-2021-05-07/evaluation-results-pytorch/iteration-17/fishMay7-trainset94shuffle5/DLC_HrnetW32_fishMay7shuffle5_detector_250_snapshot_140.h5
    bu_predictions: /home/lucas/datasets/marmoset-dlc-2021-05-07/evaluation-results-pytorch/iteration-19/marmosetMay7-trainset95shuffle1/DLC_DekrW32_marmosetMay7shuffle1_140.h5
  train:
    auto_padding:  # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
method: ctd
model:
  backbone:
    type: HRNetCoAM
    base_model_name: hrnet_w32
    pretrained: true
    coam_modules: [2,]
    channel_att_only: false
    att_heads: 1
    kpt_encoder:
      type: ColoredKeypointEncoder
      num_joints: "num_bodyparts"
      kernel_size: [15, 15]
  backbone_output_channels: 32
  heads:
    bodypart:
      type: HeatmapHead
      predictor:
        type: HeatmapPredictor
        location_refinement: false
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: "num_bodyparts"
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: false
      criterion:
        heatmap:
          type: WeightedBCECriterion
          weight: 1.0
      heatmap_config:
        channels:
        - 32
        kernel_size: []
        strides: []
        final_conv:
          out_channels: "num_bodyparts"
          kernel_size: 1