data:
  inference:
    auto_padding:  # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
    bu_predictions: /home/lucas/datasets/fish-dlc-2021-05-07/evaluation-results-pytorch/iteration-17/fishMay7-trainset94shuffle5/DLC_HrnetW32_fishMay7shuffle5_detector_250_snapshot_140.h5
  train:
    auto_padding:  # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
  bbox_margin: 25
  gen_sampling_sigmas: 0.1
  gen_sampling_symmetries: []
method: ctd
model:
  backbone:
    type: HRNetCoAM
    base_model_name: hrnet_w32
    pretrained: true
    freeze_bn_stats: false
    freeze_bn_weights: false
    coam_modules: [2,]
    channel_att_only: false
    att_heads: 1
    kpt_encoder:
      type: StackedKeypointEncoder
      num_joints: "num_bodyparts"
      kernel_size: [15, 15]
    img_size: [256, 256]
  backbone_output_channels: 32
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        #clip_scores: true
        location_refinement: false
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: "num_bodyparts"
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: false
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
      heatmap_config:
        channels:
        - 32
        kernel_size: []
        strides: []
        final_conv:
          out_channels: "num_bodyparts"
          kernel_size: 1