data:
  inference:
    auto_padding: # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
  train:
    auto_padding: # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
model:
  backbone:
    type: CondPreNet
    backbone:
      type: HRNet
      model_name: hrnet_w48
      freeze_bn_stats: true
      freeze_bn_weights: false
      interpolate_branches: false
      increased_channel_count: false  # changes backbone_output_channels to 128 when true
    kpt_encoder:
      type: ColoredKeypointEncoder
      num_joints: "num_bodyparts"
      kernel_size: [15, 15]
  backbone_output_channels: 48
  heads:
    bodypart:
      type: HeatmapHead
      weight_init: normal
      predictor:
        type: HeatmapPredictor
        apply_sigmoid: false
        #clip_scores: true
        location_refinement: false
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: "num_bodyparts"
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: false
      criterion:
        heatmap:
          type: WeightedMSECriterion
          weight: 1.0
      heatmap_config:
        channels:
        - 48
        kernel_size: []
        strides: []
        final_conv:
          out_channels: "num_bodyparts"
          kernel_size: 1