data:
  inference:
    auto_padding:  # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
  train:
    auto_padding:  # Required for HRNet backbones
      pad_width_divisor: 32
      pad_height_divisor: 32
method: ctd
model:
  backbone:
    type: HRNetCoAM
    base_model_name: hrnet_w32
    pretrained: true
    coam_modules: [2,]
    channel_att_only: false
    att_heads: 1
    kpt_encoder:
      type: ColoredKeypointEncoder
      num_joints: "num_bodyparts"
      kernel_size: [15, 15]
  backbone_output_channels: 32
  heads:
    bodypart:
      type: HeatmapHead
      predictor:
        type: HeatmapPredictor
        location_refinement: false
      target_generator:
        type: HeatmapGaussianGenerator
        num_heatmaps: "num_bodyparts"
        pos_dist_thresh: 17
        heatmap_mode: KEYPOINT
        generate_locref: false
      criterion:
        heatmap:
          type: WeightedBCECriterion
          weight: 1.0
      heatmap_config:
        channels:
        - 32
        kernel_size: []
        strides: []
        final_conv:
          out_channels: "num_bodyparts"
          kernel_size: 1