data:
  auto_padding:  # Required for HRNet backbones
    pad_width_divisor: 32
    pad_height_divisor: 32
model:
  backbone:
    type: HRNetCoAM
    base_model_name: hrnet_w48
    pretrained: true
    coam_modules: (2,)
    channel_att_only: false
    att_heads: 1
    cond_enc: colored
    num_joints: 17
  backbone_output_channels: 720
