data:
  auto_padding:  # Required for HRNet backbones
    pad_width_divisor: 32
    pad_height_divisor: 32
model:
  backbone:
    type: HRNetCoAM
    base_model_name: hrnet_w32
    pretrained: true

  backbone_output_channels: 480
