Models:
  - Name: retinanet_pvt-t_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvt-t_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 8.5
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformer
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 36.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvt-t_fpn_1x_coco/retinanet_pvt-t_fpn_1x_coco_20210831_103110-17b566bd.pth
    Paper:
      URL: https://arxiv.org/abs/2102.12122
      Title: "Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L315
      Version: 2.17.0

  - Name: retinanet_pvt-s_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvt-s_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 14.5
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformer
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 40.4
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvt-s_fpn_1x_coco/retinanet_pvt-s_fpn_1x_coco_20210906_142921-b6c94a5b.pth
    Paper:
      URL: https://arxiv.org/abs/2102.12122
      Title: "Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L315
      Version: 2.17.0

  - Name: retinanet_pvt-m_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvt-m_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 20.9
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformer
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.7
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvt-m_fpn_1x_coco/retinanet_pvt-m_fpn_1x_coco_20210831_103243-55effa1b.pth
    Paper:
      URL: https://arxiv.org/abs/2102.12122
      Title: "Pyramid Vision Transformer: A Versatile Backbone for Dense Prediction without Convolutions"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L315
      Version: 2.17.0

  - Name: retinanet_pvtv2-b0_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvtv2-b0_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 7.4
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformerV2
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 37.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b0_fpn_1x_coco/retinanet_pvtv2-b0_fpn_1x_coco_20210831_103157-13e9aabe.pth
    Paper:
      URL: https://arxiv.org/abs/2106.13797
      Title: "PVTv2: Improved Baselines with Pyramid Vision Transformer"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L543
      Version: 2.17.0

  - Name: retinanet_pvtv2-b1_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvtv2-b1_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 9.5
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformerV2
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 41.2
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b1_fpn_1x_coco/retinanet_pvtv2-b1_fpn_1x_coco_20210831_103318-7e169a7d.pth
    Paper:
      URL: https://arxiv.org/abs/2106.13797
      Title: "PVTv2: Improved Baselines with Pyramid Vision Transformer"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L543
      Version: 2.17.0

  - Name: retinanet_pvtv2-b2_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvtv2-b2_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 16.2
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformerV2
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 44.6
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b2_fpn_1x_coco/retinanet_pvtv2-b2_fpn_1x_coco_20210901_174843-529f0b9a.pth
    Paper:
      URL: https://arxiv.org/abs/2106.13797
      Title: "PVTv2: Improved Baselines with Pyramid Vision Transformer"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L543
      Version: 2.17.0

  - Name: retinanet_pvtv2-b3_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvtv2-b3_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 23.0
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformerV2
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.0
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b3_fpn_1x_coco/retinanet_pvtv2-b3_fpn_1x_coco_20210903_151512-8357deff.pth
    Paper:
      URL: https://arxiv.org/abs/2106.13797
      Title: "PVTv2: Improved Baselines with Pyramid Vision Transformer"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L543
      Version: 2.17.0

  - Name: retinanet_pvtv2-b4_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvtv2-b4_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 17.0
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformerV2
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.3
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b4_fpn_1x_coco/retinanet_pvtv2-b4_fpn_1x_coco_20210901_170151-83795c86.pth
    Paper:
      URL: https://arxiv.org/abs/2106.13797
      Title: "PVTv2: Improved Baselines with Pyramid Vision Transformer"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L543
      Version: 2.17.0

  - Name: retinanet_pvtv2-b5_fpn_1x_coco
    In Collection: RetinaNet
    Config: configs/pvt/retinanet_pvtv2-b5_fpn_1x_coco.py
    Metadata:
      Training Memory (GB): 18.7
      Epochs: 12
      Training Data: COCO
      Training Techniques:
        - SGD with Momentum
        - Weight Decay
      Training Resources: 8x NVIDIA V100 GPUs
      Architecture:
        - PyramidVisionTransformerV2
    Results:
      - Task: Object Detection
        Dataset: COCO
        Metrics:
          box AP: 46.1
    Weights: https://download.openmmlab.com/mmdetection/v2.0/pvt/retinanet_pvtv2-b5_fpn_1x_coco/retinanet_pvtv2-b5_fpn_1x_coco_20210902_201800-3420eb57.pth
    Paper:
      URL: https://arxiv.org/abs/2106.13797
      Title: "PVTv2: Improved Baselines with Pyramid Vision Transformer"
    README: configs/pvt/README.md
    Code:
      URL: https://github.com/open-mmlab/mmdetection/blob/v2.17.0/mmdet/models/backbones/pvt.py#L543
      Version: 2.17.0
