title: DeepLabCut
author: The DeepLabCut Team
logo: images/logo.png
only_build_toc_files: true

execute:
  execute_notebooks: "off"

html:
  extra_navbar: ""
  use_issues_button: true
  use_repository_button: true
  extra_footer: |
    <div>Powered by <a href="https://jupyterbook.org/">Jupyter Book</a>.</div>

repository:
  url: https://github.com/DeepLabCut/DeepLabCut
  path_to_book: docs
  branch: master

# Information about where the book exists on the web
repository:
  url                       : https://github.com/DeepLabCut/DeepLabCut/tree/master/examples  # Online location of your book
  path_to_book              : COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

launch_buttons:
  colab_url: "https://colab.research.google.com/github/AlexEMG/DeepLabCut/blob/master/examples/COLAB_YOURDATA_TrainNetwork_VideoAnalysis.ipynb"
