name: Lockfile

on:
  pull_request:
    paths:
      - "pyproject.toml"
      - "uv.lock"
      # - ".python-version"
      - ".github/workflows/uv-lockfile-check.yml"
  push:
    branches: [main]
    paths:
      - "pyproject.toml"
      - "uv.lock"
      # - ".python-version"
      - ".github/workflows/uv-lockfile-check.yml"

jobs:
  uv-lockfile-check:
    name: uv.lock is current
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: pyproject.toml

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.10.10"

      - name: Check lockfile
        run: uv lock --check
