name: publish-book

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy-book:
    uses: ./.github/workflows/build-book.yml
    with:
      publish: true
      python-version: "3.10"
      build_dir: "./_build/html"
    secrets: inherit